name: Manual Push

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Commit message"
        required: true
        default: "chore: update files"

jobs:
  push-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter with fix
        run: npm run lint:fix

      - name: Build project
        run: npm run build

      - name: Generate manifest
        run: npm run generate-manifest

      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "${{ github.event.inputs.message }}"
          git push

      - name: No changes
        if: steps.changes.outputs.has_changes == 'false'
        run: echo "No changes to commit"
