name: Push Commits

on:
  push:
    branches: [main, master, try, develop]
  pull_request:
    branches: [main, master]

jobs:
  validate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Success notification
        run: echo "✅ All checks passed - commit is valid!"
